### ISSUE TITLE
PWM error

### ISSUE THREAD

**Issue by AnatolSher** [board707/w80x_arduino#1]
Hello! PWM work not correctly. 
`
//  MultiPWM not worked. In this example, PB0 does not work correctly. However, when there is no PWM signal on the other pins, PB0 works fine.

#include <Arduino.h>
#include <stdio.h>

#define DUTY_MAX 250
#define DUTY_MIN 50

int pwm_pins[3] = { PB0, PB1, PB2 };

void setup() {
  //put your setup code here, to run once:
  pinMode(pwm_pins[0], PWM_OUT);
  pinMode(pwm_pins[1], PWM_OUT);
  pinMode(pwm_pins[2], PWM_OUT);

  analogWrite(pwm_pins[0], DUTY_MAX);
  analogWrite(pwm_pins[1], DUTY_MAX);
  analogWrite(pwm_pins[2], DUTY_MAX);
}

void loop() {
  // put your main code here, to run repeatedly:

  for (int pw = 0; pw < 3; pw++) {

    for (int i = DUTY_MAX; i > DUTY_MIN; i--) {
      analogWrite(pwm_pins[pw], i);
      delay(1);
    }
    for (int i = DUTY_MIN; i < DUTY_MAX; i++) {
      analogWrite(pwm_pins[pw], i);
      delay(1);
    }
  }
}
`

**Comment by board707** [comment]
On what board did you test it - W806 or W801 ?

**Comment by AnatolSher** [comment]
W806-Kit v1.0
and I have a parallel questions :)
where is HAL (vers 0.4.0) tutorial for W806? How can I download it? This HAL is
 present in the current build.
newest version is 0.6.0 - it is true?
![IMG_20230203_165558](https://user-images.githubusercontent.com/121094544/216621736-9d37dc04-8e2e-47a7-8bac-b01e3e5bfa83.jpg)

**Comment by board707** [comment]
Perhaps there was some misunderstanding between us :)
I have nothing to do with the manufacturers of these boards, for me it's just a hobby. So my knowledge is very limited. I only use what I found in the Net.

At the time I don't have an 806 board, only an 801. I will try to figure out the SDK for 806, but if you find something yourself, please write :)

**Comment by AnatolSher** [comment]
I understood you. It's also a hobby for me. I have an 801 board. And I will check all PWM channels on it.

**Comment by AnatolSher** [comment]
I checked. The W801 board has the same behavior. Maybe the pin multiplexing is wrong.
А по русски здесь писать можно?

**Comment by board707** [comment]
Можно :)
Но полезнее все же по английски, так как больше народу смогут участвовать.

**Comment by board707** [comment]
Did you test for the same issue under windows?

**Comment by AnatolSher** [comment]
This is independent of the operating system. I have tested compiling and uploading a PWM sketch on both Windows and Linux. Arduino IDE 1.8.19

**Comment by AnatolSher** [comment]
Странные китайские программисты... :) 
Странная концепция инициализации пинов в различных режимах... :)
Чтобы победить ошибку пришлось сделать так - при каждом вызове analogWrite() инициализировать PWM
Понятно что это костыль... Пока пусть будет так, потом ревизию кода делать будем
Лишнее за комментировал.

Strange Chinese programmers... :)
Strange concept of initializing pins in different modes... :)
To defeat the error, I had to do this - with each call to analogWrite () initialize PWM.
Banned unnecessary program lines of the function.

![image](https://user-images.githubusercontent.com/121094544/217190230-80c2d56d-fb29-4f32-b3c3-88074965abae.png)

В данный момент этот скетч работает как задумано
This sketch is currently working as intended.
![image](https://user-images.githubusercontent.com/121094544/217192301-3b58ebd2-e81e-418b-b9a8-227782792c6a.png)

**Comment by AnatolSher** [comment]
Привет! Разобрался я почему PWM в многоканальном и одновременном исполнении не работал. Пришлось всю инициализацию переписать. Чуть позже выложу исходники

**Comment by board707** [comment]
Привет
Я до конца недели в отьезде

**Comment by AnatolSher** [comment]
Исправлено в HAL 0.6.0
