### ISSUE TITLE
w801 pinout. 

### ISSUE THREAD

**Issue by AnatolSher** [board707/w80x_arduino#10]
![w801_pinout](https://user-images.githubusercontent.com/121094544/217280625-2b05cd3e-9f06-40ac-9666-59dc828704c6.png)

**Comment by board707** [comment]
Анатолий, Вы их сами рисуете или нашли где-то?
По-моему, пины PWM тут не вполне точные - возможность их переназначения зависит от корпуса, на конкретном корпусе вариантов меньше.

И еще - обратите внимание, что нижние три пина с каждой стороны идут в два ряда.

**Comment by AnatolSher** [comment]
Это nictrace c изиэлектроникс сделал. Я у него дернул. Копирайт не нарушаем :)
Дополнительные ряды - это для отладчика. Кто доползет до такого уровня - разберется.
Вот тут его статья. Он давно грызет эти камни. Он там и про пины пишет. Я бегло сравнивал даташиты. Есть разница для ремапинга. https://we.easyelectronics.ru/part/w801-zhk-ekranchik-i-lozhechka-degtya.html#cut

**Comment by board707** [comment]
Спасибо огромное, я этой статьи еще не видел. Сразу цитата из нее:

>код, скомпилированный под W801 не работает на W806. Дело в разных адресах старта образа. 

А у нас вроде работает? При настройке прошивки под линукс я брал адреса образа из СДК для 806- ого - и он отлично работает на 801м. Вы проверяли - после моих изменений прошивка 806-ого не перестала работать?

**Comment by AnatolSher** [comment]
Ну, все правильно... Мы то пользуемся сборкой SDK 806 под ардуино. C 806 -> 801 запускается. Если в CDK  я наваяю проект для 801 с его SDK, прошивка на 806 не взлетит.

**Comment by board707** [comment]
Еще одно - я в настройках в момент прошивки добавил сброс по RTS.  Для 801-ого это очень удобно. При прошивке 806 это не мешает?  Можно сделать отдельные настройки на каждый чип.
Кстати, и адреса загрузки можно тоже настроить разные - это не проблема.

**Comment by AnatolSher** [comment]
А мне все равно :) Для 806 это не принципиально, на 801 я резистор R7 удалил. Да и прошивки можно через CKLink-Lite заливать.

**Comment by board707** [comment]
Картинку добавил, но тему пока не закрываем.

**Comment by AnatolSher** [comment]
Ок
Кстати, я Nictrace не много взбудоражил :) Может и он к нашей движухе присоединится

**Comment by board707** [comment]
Проверил PWM пины по даташиту - есть незначительные расхождения, но в целом все правильно.  Хотя в будущем все равно надо бы перерисовать.
Закрываем?

**Comment by AnatolSher** [comment]
Да
Только Вы пометку сделайте в чем неточности. Я nictrace попрошу
скорректировать картинку. Его творение все же

**Comment by board707** [comment]
Я пока только ШИМ пины посмотрел. На пине PB8 на картинке не обозначен вход BRK
