### ISSUE TITLE
Is it possible to add i2s support on arduino?

### ISSUE THREAD

**Issue by coinight** [board707/w80x_arduino#17]
https://github.com/nyh-workshop/w806-i2s. Here is an example,but i have no ideal to library porting to arduino.
p.s. thanks for your hard work.

**Comment by AnatolSher** [comment]
Yes, little bit later
Now I'm investigating the possibility of making SDR radio :). w80x supports  i2s full duplex mode and this is encouraging
But first i need to make i2s codec 
[pmodi2s2_sch.pdf](https://github.com/board707/w80x_arduino/files/11782468/pmodi2s2_sch.pdf)

**Comment by board707** [comment]
@coinight 
Hi, I am starting to figure out i2s on w80x controllers. But I need an assistance from somebody, who have used i2s.
As I never dealing with it before, I need an example to test i2s on controller.
Do you have a library which you want to port to w80x or code that you require to run on our mcu ?
WBR, board707

**Comment by coinight** [comment]
Hi, board707.
Thanks for your work,but i haven't use i2s on w80x.However,I used i2s on esp32 with MAX98357A to play some sounds.The link below is a guide to drive wm8978 on esp32,
ESP32 - Intro to I2S Part 1 - XTronical(https://www.xtronical.com/i2s-ep1/)
Maybe the interface w80xduino need to have first is:

i2s_driver_install(I2S_HandleTypeDef& *i2s_config, int queue_size, void *i2s_queue)
i2s_driver_uninstall()
i2s_write_bytes(const void *src, size_t size)
int i2s_read_bytes(void *dest, size_t size)

the only example on w806 is https://github.com/nyh-workshop/w806-i2s ,Whith drives a PCM5102(also,a sound chip).
Sorry I can’t be of much help,wish your work can&nbsp;go smoothly.
WBR, coinight

@coinight
 Hi, I am starting to figure out i2s on w80x controllers. But I need an assistance from somebody, who have used i2s.
 As I never dealing with it before, I need an example to test i2s on controller.
 Do you have a library which you want to port to w80x or code that you require to run on our mcu ?
 WBR, board707

**Comment by board707** [comment]
> Maybe the interface w80xduino need to have first is:
```
i2s_driver_install(I2S_HandleTypeDef& *i2s_config, int queue_size, void *i2s_queue)
i2s_driver_uninstall()
i2s_write_bytes(const void *src, size_t size)
int i2s_read_bytes(void *dest, size_t size)
```

No, the code is not a problem.
I need some examples to test this on real hardware.
Thanks for links and for mentioning modules (MAX98357A, PCM5102) - things are a bit clearer now. I try to find such a module somewhere and test it on it.

**Comment by board707** [comment]
Hi @coinight 
I just upload to the repo a simple example sketch that playing a WAV files on W80x boards using i2s and DMA.
See the `/libraries/I2S/examples/Wav_SD_Player` folder.
The code is a port of similar ESP32 player from this link:
https://www.xtronical.com/i2s-ep3/

**Comment by board707** [comment]
Hi @coinight 
Did you test the i2s support in w80x core?
