### ISSUE TITLE
attachInterrupt error

### ISSUE THREAD

**Issue by AnatolSher** [board707/w80x_arduino#22]
Привет! Тестировщики из поднебесной нарыли ошибку.
Не верна последовательность параметров передаваемых в функцию attachInterrupt(), и нет заглушки для функции digitalPinToInterrupt(). Механизм присоединения пользовательской обработки прерывания на GPIO не соответствует текущей документации на Arduino

**Comment by board707** [comment]
А подробнее?

**Comment by AnatolSher** [comment]
Это в документации 
Syntax
attachInterrupt(digitalPinToInterrupt(pin), ISR, mode) (recommended)
attachInterrupt(interrupt, ISR, mode) (not recommended)
attachInterrupt(pin, ISR, mode) (Not recommended. Additionally, this syntax only works on Arduino SAMD Boards, Uno WiFi Rev2, Due, and 101.)
А это в нашем примере gpio interrupt
  **attachInterrupt(PB10, FALLING, &_irq_routine);**

Физически работает. Только не соответствует :)

**Comment by board707** [comment]
Понятно. Спасибо, будет исправлено в следующем релизе.

**Comment by board707** [comment]
Fixed in [0ac89f4](https://github.com/board707/w80x_arduino/commit/0ac89f4f6cdd47a006a6775c39a8ffe6c4cf716c)
