### ISSUE TITLE
Error: 13 INTERNAL: can not install w80x_duino

### ISSUE THREAD

**Issue by Chenjiek** [board707/w80x_arduino#26]
I am in China and I am unable to use the link you posted above. I am able to use it----- http://dl.isme.fun/w80x_arduino/package_w80x_index.json----- Found in Arduino

The development board for w80x, but it cannot be installed. The error is the same as the previous friend. Can you help solve some of it? Thank you!
Error: 13 INTERNAL: can not install w80x_duino:csky@2021.04.23 tool: Searching the package root directory：There is no unique root directory in the archive，find
/ ‘C:\Users\JerdeePC\AppData\Local\Arduino15\tmp\package-727441305\bin’ 和 ‘C:\Users\JerdeePC\AppData\Local\Arduino15\tmp\package-727441305\csky-elfabiv2’

**Comment by board707** [comment]
Hi
Answered in #24 :

Make sure that you **download the json file as raw** - 
https://raw.githubusercontent.com/board707/w80x_arduino/hal-v0.6.0/package_w80x_test_index.json
