### ISSUE TITLE
Can Not Download new Versions - NONE of JSONS are visible in Manage Libraries now ...

### ISSUE THREAD

**Issue by jlsilicon** [board707/w80x_arduino#29]
Can Not Download new Versions - NONE of JSONS are visible in Manage Libraries now ...

**Comment by AnatolSher** [comment]
Hello! It is work
![image](https://github.com/board707/w80x_arduino/assets/121094544/b8af171b-14ab-43ae-a912-78dc98729b49)
In preference:
https://raw.githubusercontent.com/board707/w80x_arduino/hal-v0.6.0/package_w80x_index.json
For local China users
http://dl.isme.fun/w80x_arduino/package_w80x_index.json
or
https://raw.githubusercontent.com/board707/w80x_arduino/hal-v0.6.0/package_w80x_isme_proxy_index.json

**Comment by jlsilicon** [comment]
Got it.

**Comment by jlsilicon** [comment]
Got it.
