### ISSUE TITLE
Board variants missing

### ISSUE THREAD

**Issue by ITstreet1** [board707/w80x_arduino#34]
Hi,
I have installed the latest version of the package support, but there are some boards missing. I have support for only 
W801, W805, W806, and Air103. I don't have for Air101, W800, and W802. I tried to reinstall the package, but it is the same.

Any suggestion?

Regards

**Comment by board707** [comment]
Air101 should be there, w800/802 boards are not supported

**Comment by ITstreet1** [comment]
Air101 is not there. I used this link
https://raw.githubusercontent.com/board707/w80x_arduino/hal-v0.6.0/package_w80x_index.json

Edit:
W800/802 are not supported, but they are here in variants?

**Comment by board707** [comment]
I apologize for the confusion, I was wrong, boards W800 and W802, as well as air101, are in the package and are supported.
However, these boards were included in the package later than revision 0.0.5, so if you install the package via a link, you will not have these boards. They will be included in the next release.

Alternative way - you can download the latest package version through the "Code - Download as ZIP" button and install it in the package directory manually.

**Comment by ITstreet1** [comment]
But the JSON links say 0.6.0. ?

**Comment by board707** [comment]
"0.6.0" is a version of HAL
The latest Arduino package has a version number 0.0.5

**Comment by ITstreet1** [comment]
Anyway, made it manually. It works

PC.
When should we expect the 0.6.0?

**Comment by ITstreet1** [comment]
Just noticed, no support for Air105. Any plans to add it?

**Comment by board707** [comment]
As far I know Air105 based on completely different core and not compatible with WinnnerMicro SDK. So it's unlikely that it will ever be supported.

**Comment by ITstreet1** [comment]
When should we expect the 0.6.0?

**Comment by board707** [comment]
I can not tell. It depends not only on me, we have several people on the team. I think within 1-2 weeks

**Comment by ITstreet1** [comment]
Thank you.

**Comment by board707** [comment]
Version 0.0.6 released.
