### ISSUE TITLE
The system crashes when ADC and hw i2c are used at the same time

### ISSUE THREAD

**Issue by Chenjiek** [board707/w80x_arduino#39]
Thank you for helping me solve the problem. I am currently encountering a situation where the LED screen SSD1306 of U8G2 using PA1 and PA4 as hardware I2C freezes when reading the ADC voltage. You can use software to simulate I2C at other pins, but the refresh rate displayed is too slow. We look forward to resolving this issue soon. Thank you!

**Comment by AnatolSher** [comment]
你好 :)
Replace these files in your Arduino package, test and tell us the result
[Change_this.zip](https://github.com/board707/w80x_arduino/files/15143592/Change_this.zip)

**Comment by Chenjiek** [comment]
Okay, I did a simple compilation and encountered an error. I will send the error message below:
C:\Users\Administrator\AppData\Local\Arduino15\packages\w80x_duino\hardware\XT804\0.0.6\cores\w806\HardwareI2C.cpp:2:25: fatal error: HardwareI2C.h: No such file or directory
 #include "HardwareI2C.h"
                         ^
compilation terminated.

exit status 1

Compilation error: exit status 1

**Comment by AnatolSher** [comment]
Hi! If you are using Windows, you need to rewrite the files in the following folders:
C:\Users\User\AppData\Local\Arduino15\packages\w80x_duino\hardware\XT804\0.0.6\libraries\Wire <- HardwareI2C.cpp
C:\Users\User\AppData\Local\Arduino15\packages\w80x_duino\hardware\XT804\0.0.6\cores\w806 <- Arduino.c
C:\Users\User\AppData\Local\Arduino15\packages\w80x_duino\hardware\XT804\0.0.6\cores\w806\lib\drivers <- wm_adc.c
Where User - your login in Windows

**Comment by Chenjiek** [comment]
I didn't understand what you meant, I don't know where to start, sorry, I can't understand......

**Comment by Chenjiek** [comment]
Okay, I found the path and it's already being compiled. Wait a moment, I'll give it a try..

**Comment by AnatolSher** [comment]
For maximum speed hw i2c
![image](https://github.com/board707/w80x_arduino/assets/121094544/5aa7f89e-1b87-4ea0-8d81-333cabf88a97)

**Comment by Chenjiek** [comment]
![QQ图片20240429170436](https://github.com/board707/w80x_arduino/assets/126390784/f64ecb7d-49bb-4af4-a11c-ca52d962f1e0)
![MN5](https://github.com/board707/w80x_arduino/assets/126390784/8d8faf36-5ded-4d95-8045-bf9bfdf7175e)
Yes, I tested it for a long time just now and it seems that the conflict between AD input and I2C has been resolved. The screen refresh speed is very fast, which can be described as very, very beautiful. Thank you very much for your help. Thank you, but I have a question. Why is the lowest voltage of this ADC not 0V, but 19mv?

**Comment by AnatolSher** [comment]
Hmm... Very beautiful girl :)

To use ADC correctly, you need to study Chapter 26 of the datasheet for w80x chips. Individual calibration is required for accurate measurements. The calibration technique was described in a question on ask.winnermicro.com. I don't remember exactly. HAL provides simplified ADC management. More advanced control is implemented in the W800-SDK provided by WinnerMicro.

**Comment by Chenjiek** [comment]
Okay, it looks like some advanced knowledge. Thank you. This has already been completed. Do I also need to close it?

**Comment by AnatolSher** [comment]
Yes
Good luck

**Comment by board707** [comment]
Fixed in 5d60d5c
