### ISSUE TITLE
HAL GPIO examples. Add to Examples folder pls

### ISSUE THREAD

**Issue by AnatolSher** [board707/w80x_arduino#6]
Worked in HAL v. "0.4.0" and v. "0.6.0". Tested in Win/Lin, IDE 2.0.3/1.8.19
[hal_led.ZIP](https://github.com/board707/w80x_arduino/files/10610719/hal_led.ZIP)
[hal_gpio_led_interrupt.ZIP](https://github.com/board707/w80x_arduino/files/10610721/hal_gpio_led_interrupt.ZIP)

**Comment by board707** [comment]
Hi
Did you tested the code with interrupt?

**Comment by AnatolSher** [comment]
Yes. On 806 board work fine
