### ISSUE TITLE
Adapted example from SDK (HAL v "0.6.0") - Beautiful transfusion of light :)

### ISSUE THREAD

**Issue by AnatolSher** [board707/w80x_arduino#8]
[hal_pwm_led_Beautiful.zip](https://github.com/board707/w80x_arduino/files/10662525/hal_pwm_led_Beautiful.zip)

**Comment by board707** [comment]
I suggest that this example not be included in the release. The purpose of our examples is to illustrate the work with hal., and the PVM settings functions in this code are completely coincide with the example hal_pwm_led.

**Comment by AnatolSher** [comment]
Не вопрос :) Можно закрывать
No problem
